### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by bymbhaskar** [PRBonn/depth_clustering#62]
I am unable to build using ROS Kinetic (ubuntu 16.04).
Showing following error:
 error: call of overloaded ‘make_shared<PclCloud>(PclCloud&)’ is ambiguous
   return make_shared<PclCloud>(pcl_cloud);
                                         ^
![error](https://user-images.githubusercontent.com/42085589/74307429-4adcd200-4d8b-11ea-9e7b-3f261e832ed2.png)

**Comment by niosus** [comment]
Oh, strange. Could you modify this code with `boost::make_shared` instead of a simple `make_shared` and see if this helps? Strange that it builds on Ubuntu 18.04 though...

**Comment by bymbhaskar** [comment]
Thank you for your quick response. 
I tried with boost::make_shared. It still didn't work..
error is as follows:  

/home/bhaskar/catkin_ws/devel/.private/depth_clustering/lib/libfolder_reader.so: undefined reference to `boost::re_detail::cpp_regex_traits_implementation<char>::transform[abi:cxx11](char const*, char const*) const'
/home/bhaskar/catkin_ws/devel/.private/depth_clustering/lib/libfolder_reader.so: undefined reference to `boost::re_detail::cpp_regex_traits_implementation<char>::transform_primary[abi:cxx11](char const*, char const*) const'
collect2: error: ld returned 1 exit status


![err_boost](https://user-images.githubusercontent.com/42085589/74360035-590e0b00-4dea-11ea-8bbe-615fa16f2829.JPG)

**Comment by bymbhaskar** [comment]
able to build now.
Thanks

**Comment by niosus** [comment]
Could you point out the changes you had to make?

**Comment by bymbhaskar** [comment]
I just went for Ubuntu 18.04 and was able to build

**Comment by niosus** [comment]
Thanks for the update. It's still weird that you could not build on other versions of Ubuntu though...

**Comment by DavidZhaoP** [comment]
> Oh, strange. Could you modify this code with `boost::make_shared` instead of a simple `make_shared` and see if this helps? Strange that it builds on Ubuntu 18.04 though...

I met the same problem, and i follow your solution by ,modify this code with boost::make_shared instead of a simple make_shared.
But another problem happened,like this 
![Screenshot from 2022-02-13 14-30-56](https://user-images.githubusercontent.com/38452932/153741752-62ec2824-479a-401c-8fb0-e8369a0f714e.png)

Can you give me some help? Thanks

**Comment by DavidZhaoP** [comment]
> > Oh, strange. Could you modify this code with `boost::make_shared` instead of a simple `make_shared` and see if this helps? Strange that it builds on Ubuntu 18.04 though...
> 
> I met the same problem, and i follow your solution by ,modify this code with boost::make_shared instead of a simple make_shared. But another problem happened,like this ![Screenshot from 2022-02-13 14-30-56](https://user-images.githubusercontent.com/38452932/153741752-62ec2824-479a-401c-8fb0-e8369a0f714e.png)
> 
> Can you give me some help? Thanks
 
problem solved!
use std::make_shared instead of using boost::make_shared .
